- Egg puzzle Problem
- Lexicographically minimum string rotation
- Quick Sort/Python.py
- Rotate bits of a number
- Selection_Sort/python
I have made the file of Selection sort In python Language , Please add it!
> Issues #55 , #91 , #92 , #93

- C++/binary_search.cpp
- Python/list_reverse.py
Created list_reverse.py issue#13
> created list_reverse.py

- C++/Sieve_of_Eratosthenes.cpp
- C++/binary_search.cpp
- Python/Linear_Search.py
- Python/list_reverse.py
Algorithm for Seive of Eratosthenes
issue #45 solved
> Seive of eratosthenes

- C++/binary_search.cpp
- Python/Linear_Search.py
- Python/list_reverse.py
Written the algorithm for linear search
Issue #42
> Linear search

- C++/Prime with complexity O(sqrt(n)).cpp
- C++/Selection Sort.cpp
- C/Alternate Pattern.c
- C/Merge Sort.c
- C/Recursive HCF.c
- C/Selection Sort.c
- C/Toggle_Bits_except_one.c
- C/maxOccuringCharacterInString.c
- Java/Kaprekar.java
- Java/Spirally traversing a matrix.java
I have added simple codes for the beginning and I will add more codes.
> Added two programming language folder with simple algorithm

- stack.cpp
> infix to prefix notation

- BSTcpp.cpp
- Singlelist.cpp
- XorSwap.cpp
- inpe.c
- palincount.cpp
Solved Issue no: 25,12,8 and 4
> Issues : #25 #12 #8 #4 #64

- Python/Armstrong_number.py
- Python/min_ num list in python.py
> smallest no in the list in python

- EgyptianFractions.cpp
- EgyptianFractions.java
Added Algorithm in Java and C++ language
> Added Egyptian Fractions Algorithm

- Python/Armstrong_number.py
- Python/min_element without inbuilt function.py
- c++/partial_sort.cpp
- c++/pascaltriangle.cpp
- c++/radix_sort.cpp
> check armstrong number using python

- linked list/linkedlist.cpp
For issue #4 
Added the basic function for a linked list
> linkedlist basic in c++

- Kadane/kadane.cpp
Added kadane algo in c++
Closes #50
> Add kadane algorithm

- Dijkstra’s in cpp/Dij.cpp
- Floyd Warshall in cpp/floyd.cpp
- Prim's in cpp/prim.cpp
solves #101 
solves #103 
solves #104
> Dijkstra’s in cpp

- pascal's triangle
pascal triangle 
[pascal triangle.zip](https://github.com/JGEC-Winter-of-Code-JWoC/JWoC_Algorithms/files/4244876/pascal.triangle.zip)
in c programming
> pascal's triangle issue #69

- SieveofEratosthenes.c
- SieveofEratosthenes.cpp
> Add sieve of Eratosthenes in C and C++

- counting sort
> counting short #87

- prim's algorithm
> prim's algorithm

- Java/LeftShift.java
Created LeftShift.java for issue #94
> Created LeftShift.java

- C/BinarySearch.c
- C/InterpolationSearch.c
- C/JumpSearch.c
- C/LinearSearch.c
Added some popular searching algorithms in C . 
It would be really appriciated if this PR merged.
issue: #114
> Searching Algorithms in C 

- String_Hashing/z-algorithm.cpp
Changed from
cin<<tar<<pat;
to 
cin>>tar>>pat;
> cin signs changed to Greater
